### ISSUE TITLE
Httpclient crashed

### ISSUE THREAD

**Issue by rekola** [Sometrik/httpclient#27]
LinkCleaner: loaded https://item.rakuten.co.jp/book/14894352/?scid=af_pc_etc&sc2id=af_101_0_0 (status = 0
got miner exception (fail): HTTP request failed: 
HTTP request failed (ec = 0, s1 = 1, s2 = 0): 
terminating load due to idle()
lister: ../httpclient/src/CurlClient.cpp:240: static int CurlClient::progress_func(void*, double, double, double, double): Assertion `callback' failed.
fish: Job 2, “./lister” terminated by signal SIGABRT (Abort)

**Comment by rekola** [comment]
Another crash:

0x00000000005d2688 in CurlClient::progress_func(void*, double, double, double, double) ()
(gdb) bt
#0  0x00000000005d2688 in CurlClient::progress_func(void*, double, double, double, double) ()
#1  0x00007ffff7b75579 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#2  0x00007ffff7b759e4 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#3  0x00007ffff7b8b0f8 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#4  0x00007ffff7b9e5d7 in curl_multi_remove_handle () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#5  0x00007ffff7b8ab0a in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#6  0x00000000005d3119 in CurlClient::~CurlClient() ()
#7  0x00000000004fdd38 in LoaderThread::~LoaderThread() ()
#8  0x0000000000410dbe in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#9  0x00000000004e81a2 in LoadContextInterface::handleThreadResultEvent(ThreadResultEvent const&) ()
